/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardMemberIndexRouteImport } from './routes/dashboard/member/index'
import { Route as DashboardEmployerIndexRouteImport } from './routes/dashboard/employer/index'
import { Route as DashboardMemberProfileRouteImport } from './routes/dashboard/member/profile'
import { Route as DashboardMemberContributionsRouteImport } from './routes/dashboard/member/contributions'
import { Route as DashboardMemberAccountsRouteImport } from './routes/dashboard/member/accounts'
import { Route as DashboardEmployerProfileRouteImport } from './routes/dashboard/employer/profile'
import { Route as DashboardEmployerEmployeesRouteImport } from './routes/dashboard/employer/employees'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/_auth/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMemberIndexRoute = DashboardMemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployerIndexRoute = DashboardEmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemberProfileRoute = DashboardMemberProfileRouteImport.update({
  id: '/member/profile',
  path: '/member/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMemberContributionsRoute =
  DashboardMemberContributionsRouteImport.update({
    id: '/member/contributions',
    path: '/member/contributions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMemberAccountsRoute = DashboardMemberAccountsRouteImport.update({
  id: '/member/accounts',
  path: '/member/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmployerProfileRoute =
  DashboardEmployerProfileRouteImport.update({
    id: '/employer/profile',
    path: '/employer/profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmployerEmployeesRoute =
  DashboardEmployerEmployeesRouteImport.update({
    id: '/employer/employees',
    path: '/employer/employees',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/dashboard': typeof DashboardLayoutRoute
  '/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/employer/employees': typeof DashboardEmployerEmployeesRoute
  '/dashboard/employer/profile': typeof DashboardEmployerProfileRoute
  '/dashboard/member/accounts': typeof DashboardMemberAccountsRoute
  '/dashboard/member/contributions': typeof DashboardMemberContributionsRoute
  '/dashboard/member/profile': typeof DashboardMemberProfileRoute
  '/dashboard/employer': typeof DashboardEmployerIndexRoute
  '/dashboard/member': typeof DashboardMemberIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/': typeof PublicIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/employer/employees': typeof DashboardEmployerEmployeesRoute
  '/dashboard/employer/profile': typeof DashboardEmployerProfileRoute
  '/dashboard/member/accounts': typeof DashboardMemberAccountsRoute
  '/dashboard/member/contributions': typeof DashboardMemberContributionsRoute
  '/dashboard/member/profile': typeof DashboardMemberProfileRoute
  '/dashboard/employer': typeof DashboardEmployerIndexRoute
  '/dashboard/member': typeof DashboardMemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/employer/employees': typeof DashboardEmployerEmployeesRoute
  '/dashboard/employer/profile': typeof DashboardEmployerProfileRoute
  '/dashboard/member/accounts': typeof DashboardMemberAccountsRoute
  '/dashboard/member/contributions': typeof DashboardMemberContributionsRoute
  '/dashboard/member/profile': typeof DashboardMemberProfileRoute
  '/dashboard/employer/': typeof DashboardEmployerIndexRoute
  '/dashboard/member/': typeof DashboardMemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-otp'
    | '/dashboard'
    | '/'
    | '/dashboard/'
    | '/api/trpc/$'
    | '/dashboard/employer/employees'
    | '/dashboard/employer/profile'
    | '/dashboard/member/accounts'
    | '/dashboard/member/contributions'
    | '/dashboard/member/profile'
    | '/dashboard/employer'
    | '/dashboard/member'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify-otp'
    | '/dashboard'
    | '/'
    | '/api/trpc/$'
    | '/dashboard/employer/employees'
    | '/dashboard/employer/profile'
    | '/dashboard/member/accounts'
    | '/dashboard/member/contributions'
    | '/dashboard/member/profile'
    | '/dashboard/employer'
    | '/dashboard/member'
  id:
    | '__root__'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/verify-otp'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/_public/'
    | '/dashboard/'
    | '/api/trpc/$'
    | '/dashboard/employer/employees'
    | '/dashboard/employer/profile'
    | '/dashboard/member/accounts'
    | '/dashboard/member/contributions'
    | '/dashboard/member/profile'
    | '/dashboard/employer/'
    | '/dashboard/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/member/': {
      id: '/dashboard/member/'
      path: '/member'
      fullPath: '/dashboard/member'
      preLoaderRoute: typeof DashboardMemberIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employer/': {
      id: '/dashboard/employer/'
      path: '/employer'
      fullPath: '/dashboard/employer'
      preLoaderRoute: typeof DashboardEmployerIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/member/profile': {
      id: '/dashboard/member/profile'
      path: '/member/profile'
      fullPath: '/dashboard/member/profile'
      preLoaderRoute: typeof DashboardMemberProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/member/contributions': {
      id: '/dashboard/member/contributions'
      path: '/member/contributions'
      fullPath: '/dashboard/member/contributions'
      preLoaderRoute: typeof DashboardMemberContributionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/member/accounts': {
      id: '/dashboard/member/accounts'
      path: '/member/accounts'
      fullPath: '/dashboard/member/accounts'
      preLoaderRoute: typeof DashboardMemberAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employer/profile': {
      id: '/dashboard/employer/profile'
      path: '/employer/profile'
      fullPath: '/dashboard/employer/profile'
      preLoaderRoute: typeof DashboardEmployerProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/employer/employees': {
      id: '/dashboard/employer/employees'
      path: '/employer/employees'
      fullPath: '/dashboard/employer/employees'
      preLoaderRoute: typeof DashboardEmployerEmployeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEmployerEmployeesRoute: typeof DashboardEmployerEmployeesRoute
  DashboardEmployerProfileRoute: typeof DashboardEmployerProfileRoute
  DashboardMemberAccountsRoute: typeof DashboardMemberAccountsRoute
  DashboardMemberContributionsRoute: typeof DashboardMemberContributionsRoute
  DashboardMemberProfileRoute: typeof DashboardMemberProfileRoute
  DashboardEmployerIndexRoute: typeof DashboardEmployerIndexRoute
  DashboardMemberIndexRoute: typeof DashboardMemberIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEmployerEmployeesRoute: DashboardEmployerEmployeesRoute,
  DashboardEmployerProfileRoute: DashboardEmployerProfileRoute,
  DashboardMemberAccountsRoute: DashboardMemberAccountsRoute,
  DashboardMemberContributionsRoute: DashboardMemberContributionsRoute,
  DashboardMemberProfileRoute: DashboardMemberProfileRoute,
  DashboardEmployerIndexRoute: DashboardEmployerIndexRoute,
  DashboardMemberIndexRoute: DashboardMemberIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
